fix: make compatible with IPM v0.9
intersystems/isc-ipm-js pull request #20
Opened 2024-12-05 17:54 UTC by isc-shuliu

2025-01-22 21:26 UTC, isc-pbarton requested changes

2025-01-22 21:26 UTC, isc-pbarton commented on cls/pkg/isc/ipm/js/base/processor.cls
> +	If ##class(%Dictionary.Definintion).%ExistsId("%IPM.Utils.File") {
Typo here causes copying files to fail, should be Definition

2025-01-22 22:07 UTC, isc-pbarton approved these changes

2025-01-23 13:31 UTC, isc-tleavitt approved these changes

2025-01-23 13:35 UTC, merged